### 0. 各種変数
@User_Key=
@tenantName=
@Client_Id=
@access_token=
@ReleaseKey=

### 1. トークン取得
POST https://account.uipath.com/oauth/token HTTP/1.1
Content-Type: application/json
X-UIPATH-TenantName: {{tenantName}}

{
  "grant_type": "refresh_token", 
  "client_id": "{{Client_Id}}", 
  "refresh_token": "{{User_Key}}"
}

### 2. ReleaseKey取得
GET https://platform.uipath.com/odata/Releases HTTP/1.1
Authorization: Bearer {{access_token}}
X-UIPATH-TenantName: {{tenantName}}

### 3. ジョブ実行
POST https://platform.uipath.com/odata/Jobs/UiPath.Server.Configuration.OData.StartJobs HTTP/1.1
Authorization: Bearer {{access_token}}
X-UIPATH-TenantName: {{tenantName}}
Content-Type: application/json

{
  "startInfo": {
    "ReleaseKey": "{{ReleaseKey}}",
    "Strategy": "All",
    "RobotIds": [],
    "NoOfRobots": 0,
    "InputArguments": "{\"message\":\"コマンドから実行！\"}"
  }
}